book/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from .views import index, add, get, edit, update, delete, indexuser, reserve_book,return_book,change_visibility

urlpatterns = [
    path('', index, name='view_books'),
    path('userview/', indexuser, name='view_books_user'),
    path('add/', add, name='add_book'),
    path('<int:id>/', get, name='get_book'),
    path('edit/<int:id>/', edit, name='edit_book'),
    path('update/<int:id>/', update, name='update_book'),
    path('delete/<int:id>/', delete, name='delete_book'),
    path('reserve/<int:id>/', reserve_book, name='reserve_book'),
    path('return/<int:id>/', return_book, name='return_book'),
    path('changeVisibility/<int:id>/', change_visibility, name='change_visibility')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

libraryManagementSystem/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('book.urls')),
    path('',include('home.urls')),
    path('', include('authentication.urls')),
    path('reservations/', include('reservations.urls')),
    path('users/', include('user.urls'))

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from user.views import view_user_profile, view_all_users, view_user_profile_id,update_user,user_details_admin,change_user_state

urlpatterns = [
    path('user/', view_user_profile, name='view_user_profile'),
    path('', view_all_users, name='view_all_users'),
    path('user/<int:id>/', view_user_profile_id,name="view_user_profile_id"),
    path('update/<int:id>/', update_user, name="update_user"),
    path('userDetailsAdmin/<int:id>/', user_details_admin, name="user_details_admin"),
    path('changeUserState/<int:id>/', change_user_state, name="change_user_state"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

user/models.py
from django.contrib.auth.models import User
from django.db import models

class CustomUser(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    street = models.CharField(max_length=100)
    city =  models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images/')

user/forms.py
from django.forms import ModelForm
from django.forms import  widgets, ModelForm
from user.models import CustomUser


class UserForms(ModelForm):
    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'phone', 'street','city','state','zip_code','image']

user/views.py
import logging

from django.contrib import messages
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404

from user.forms import UserForms
from user.models import CustomUser
logger = logging.getLogger(__name__)

def view_all_users(request):
    p = Paginator(CustomUser.objects.all(), 8)
    page = request.GET.get('page')
    users = p.get_page(page)
    context = {'users': users}
    return render(request, 'user/allusers.html', context)


def view_user_profile(request):
    user = User.objects.get(username=request.user)
    custom_user = CustomUser.objects.get(user=user)
    context = {'custom_user': custom_user}
    return render(request, 'user/userdetails.html', context)


def view_user_profile_id(request, id):
    custom_user = CustomUser.objects.get(id=id)
    context = {'custom_user': custom_user}
    return render(request, 'user/userdetails.html', context)

def update_user(request, id):

    if request.method == 'POST':
        user =get_object_or_404(CustomUser, id=id)
        # user = CustomUser.objects.filter(id=id)
        form = UserForms(request.POST or None, request.FILES,instance=user)

        if form.is_valid():
            form.save()
            messages.success(request, "Updated successfully")
            return redirect('view_books')

            # CustomUser.objects.filter(id=id).update(
            # first_name= request.POST['first_name'],
            # last_name = request.POST['last_name'],
            # phone = request.POST['phone'],
            # street = request.POST['street'],
            # city = request.POST['city'],
            # state = request.POST['state'],
            # zip_code = request.POST['zip_code'],
            # image = request.FILES['image']
        # )

    # messages.success(request, "Updated successfully" )
    return redirect('view_user_profile')

def user_details_admin(request, id):
    custom_user = CustomUser.objects.get(id=id)
    context = {'custom_user': custom_user}
    return render(request, 'user/userdetailsadmin.html', context)

def change_user_state(request, id):

    custom_user = get_object_or_404(CustomUser, id=id)
    if custom_user.user.is_active:
        custom_user.user.is_active = False
        logger.warning('User is deactivated')
    else:
        custom_user.user.is_active = True
        logger.warning('User is activated')
    custom_user.user.save()
    return redirect('view_all_users')

templates/user/allusers.html
{% extends 'base.html' %}
{% block content %}

<style>
  body{
    background-color: #f8f9fa!important
}
.p-4 {
    padding: 1.5rem!important;
}
.mb-0, .my-0 {
    margin-bottom: 0!important;
}
.shadow-sm {
    box-shadow: 0 .125rem .25rem rgba(0,0,0,.075)!important;
}
}
/* user-dashboard-info-box */
.user-dashboard-info-box .candidates-list .thumb {
    margin-right: 20px;
}
.user-dashboard-info-box .candidates-list .thumb img {
    width: 80px;
    height: 80px;
    -o-object-fit: cover;
    object-fit: cover;
    overflow: hidden;
    border-radius: 50%;
}

.user-dashboard-info-box .title {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-align: center;
    -ms-flex-align: center;
    align-items: center;
    padding: 30px 0;
}

.user-dashboard-info-box .candidates-list td {
    vertical-align: middle;
}

.user-dashboard-info-box td li {
    margin: 0 4px;
}

.user-dashboard-info-box .table thead th {
    border-bottom: none;
}

.table.manage-candidates-top th {
    border: 0;
}

.user-dashboard-info-box .candidate-list-favourite-time .candidate-list-favourite {
    margin-bottom: 10px;
}

.table.manage-candidates-top {
    min-width: 650px;
}

.user-dashboard-info-box .candidate-list-details ul {
    color: #969696;
}

/* Candidate List */
.candidate-list {
    background: #ffffff;
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    border-bottom: 1px solid #eeeeee;
    -webkit-box-align: center;
    -ms-flex-align: center;
    align-items: center;
    padding: 20px;
    -webkit-transition: all 0.3s ease-in-out;
    transition: all 0.3s ease-in-out;
}
.candidate-list:hover {
    -webkit-box-shadow: 0px 0px 34px 4px rgba(33, 37, 41, 0.06);
    box-shadow: 0px 0px 34px 4px rgba(33, 37, 41, 0.06);
    position: relative;
    z-index: 99;
}
.candidate-list:hover a.candidate-list-favourite {
    color: #e74c3c;
    -webkit-box-shadow: -1px 4px 10px 1px rgba(24, 111, 201, 0.1);
    box-shadow: -1px 4px 10px 1px rgba(24, 111, 201, 0.1);
}

.candidate-list .candidate-list-image {
    margin-right: 25px;
    -webkit-box-flex: 0;
    -ms-flex: 0 0 80px;
    flex: 0 0 80px;
    border: none;
}
.candidate-list .candidate-list-image img {
    width: 80px;
    height: 80px;
    -o-object-fit: cover;
    object-fit: cover;
}

.candidate-list-title {
    margin-bottom: 5px;
}

.candidate-list-details ul {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
    margin-bottom: 0px;
}
.candidate-list-details ul li {
    margin: 5px 10px 5px 0px;
    font-size: 13px;
}

.candidate-list .candidate-list-favourite-time {
    margin-left: auto;
    text-align: center;
    font-size: 13px;
    -webkit-box-flex: 0;
    -ms-flex: 0 0 90px;
    flex: 0 0 90px;
}
.candidate-list .candidate-list-favourite-time span {
    display: block;
    margin: 0 auto;
}
.candidate-list .candidate-list-favourite-time .candidate-list-favourite {
    display: inline-block;
    position: relative;
    height: 40px;
    width: 40px;
    line-height: 40px;
    border: 1px solid #eeeeee;
    border-radius: 100%;
    text-align: center;
    -webkit-transition: all 0.3s ease-in-out;
    transition: all 0.3s ease-in-out;
    margin-bottom: 20px;
    font-size: 16px;
    color: #646f79;
}
.candidate-list .candidate-list-favourite-time .candidate-list-favourite:hover {
    background: #ffffff;
    color: #e74c3c;
}

.candidate-banner .candidate-list:hover {
    position: inherit;
    -webkit-box-shadow: inherit;
    box-shadow: inherit;
    z-index: inherit;
}

.bg-white {
    background-color: #ffffff !important;
}
.p-4 {
    padding: 1.5rem!important;
}
.mb-0, .my-0 {
    margin-bottom: 0!important;
}
.shadow-sm {
    box-shadow: 0 .125rem .25rem rgba(0,0,0,.075)!important;
}

.user-dashboard-info-box .candidates-list .thumb {
    margin-right: 20px;
}
</style>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css" integrity="sha256-2XFplPlrFClt0bIdPgpz8H7ojnk10H69xRqd9+uTShA=" crossorigin="anonymous" />
<div class="container mt-3 mb-4">
<div class="col-lg-9 mt-4 mt-lg-0">
    <div class="row">
      <div class="col-md-12">
        <div class="user-dashboard-info-box table-responsive mb-0 bg-white p-4 shadow-sm">
          <table class="table manage-candidates-top mb-0">
            <thead>
              <tr>
                <th>User Name</th>
                <th class="text-center">Status</th>
                <th class="action text-right">Action</th>
              </tr>
            </thead>
            <tbody>
            {% for u in users %}
              <tr class="candidates-list">
                <td class="title">
                  <div class="thumb">
                    <img class="img-fluid" src={{u.image.url}} alt="">
                  </div>
                  <div class="candidate-list-details">
                    <div class="candidate-list-info">
                      <div class="candidate-list-title">
                        <h5 class="mb-0"><a >{{u.first_name}} {{u.last_name}}</a></h5>
                      </div>
                      <div class="candidate-list-option">
                        <ul class="list-unstyled">
                          <li><i class="fas fa-filter pr-1"></i>{{u.user.email}}</li>
                          <li><i class="fas fa-map-marker-alt pr-1"></i> {{u.city}}, {{u.state}} {{u.zip_code}}</li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </td>
                <td class="candidate-list-favourite-time text-center">
                  {% if u.user.is_active %}

                   <a class="candidate-list-favourite order-2 text-danger" ><i class="fas fa-heart"></i></a>
                  <span class="candidate-list-time order-1">Active</span>
                  {%else%}


                  <span class="candidate-list-time order-1">Deactivated</span>
                  {% endif %}
                </td>
                <td>
                  <ul class="list-unstyled mb-0 d-flex justify-content-end">
                    <li><a  onclick="location.href='{% url 'user_details_admin' u.id %}'" class="text-primary" data-toggle="tooltip" title="" data-original-title="view"><i class="far fa-eye"></i></a></li>
                     {%if u.user.is_active %}

                    <li><a onclick="location.href='{% url 'change_user_state' u.id %}'" class="text-danger" data-toggle="tooltip" title="" data-original-title="Delete"><i class="fas fa-heart"></i></a></li>

                    {%else%}
                    <li><a onclick="location.href='{% url 'change_user_state' u.id %}'" class="text-danger" data-toggle="tooltip" title="" data-original-title="Delete"><i class="far fa-heart"></i></a></li>
                    {%endif%}
                    <li><a href="#" class="text-danger" data-toggle="tooltip" title="" data-original-title="Delete"><i class="far fa-trash-alt"></i></a></li>
                  </ul>
                </td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
              <!--pagination-->
        {{users}}
        {%if users.has_previous %}
        <a href="?page=1">&laquo First</a>
        <a href="?page={{ users.previous_page_number }}">Previous</a>
        {% endif %}
        {% if users.has_next %}
        <a href="?page={{ users.next_page_number }}">Next</a>
        <a href="?page={{users.paginator.num_pages }}">Last &raquo</a>
        {% endif %}
<!-- end pagination-->
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/user/userdetails.html
{% extends 'base.html' %}
{% block content %}

<style>
body {
    margin: 0;
    color: #2e323c;
    background: #f5f6fa;
    position: relative;
    height: 100%;
}
.account-settings .user-profile {
    margin: 0 0 1rem 0;
    padding-bottom: 1rem;
    text-align: center;
}
.account-settings .user-profile .user-avatar {
    margin: 0 0 1rem 0;
}
.account-settings .user-profile .user-avatar img {
    width: 90px;
    height: 90px;
    -webkit-border-radius: 100px;
    -moz-border-radius: 100px;
    object-fit: cover;
    border-radius: 100px;
}
.account-settings .user-profile h5.user-name {
    margin: 0 0 0.5rem 0;
}
.account-settings .user-profile h6.user-email {
    margin: 0;
    font-size: 0.8rem;
    font-weight: 400;
    color: #9fa8b9;
}
.account-settings .about {
    margin: 2rem 0 0 0;
    text-align: center;
}
.account-settings .about h5 {
    margin: 0 0 15px 0;
    color: #007ae1;
}
.account-settings .about p {
    font-size: 0.825rem;
}
.form-control {
    border: 1px solid #cfd1d8;
    -webkit-border-radius: 2px;
    -moz-border-radius: 2px;
    border-radius: 2px;
    font-size: .825rem;
    background: #ffffff;
    color: #2e323c;
}

.card {
    background: #ffffff;
    -webkit-border-radius: 5px;
    -moz-border-radius: 5px;
    border-radius: 5px;
    border: 0;
    margin-bottom: 1rem;
}
</style>

<div class="container">
<div class="row gutters">
<div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
<div class="card h-100">
	<div class="card-body">
		<div class="account-settings">
			<div class="user-profile">
				<div class="user-avatar">
					<img src={{custom_user.image.url}} alt="Maxwell Admin">
				</div>
				<h5 class="user-name">{{custom_user.first_name}} {{custom_user.last_name}}</h5>
				<h6 class="user-email">{{custom_user.user.email}}</h6>
			</div>
<!--			<div class="about">-->
<!--				<h5>About {{user.is_staff}}</h5>-->
<!--				<p>I'm Yuki. Full Stack Designer I enjoy creating user-centric, delightful and human experiences.</p>-->
<!--			</div>-->
		</div>
	</div>
</div>
</div>
<div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
<div class="card h-100">
	<form action="/users/update/{{custom_user.id}}/" method="post" enctype="multipart/form-data">
		  {% csrf_token %}
	<div class="card-body">
		<div class="row gutters">
			<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
				<h6 class="mb-2 text-primary">Personal Details</h6>
			</div>

			<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
				<div class="form-group">
					<label for="fullName">First Name</label>
					<input type="text" class="form-control" id="fullName" placeholder="Enter first name" name="first_name" value="{{custom_user.first_name}}">
				</div>
			</div>
			<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
				<div class="form-group">
					<label for="eMail">Email</label>
					<input type="email" class="form-control" id="eMail" placeholder="Enter email ID" name="email" value="{{custom_user.user.email}}">
				</div>
			</div>
			<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
				<div class="form-group">
					<label for="phone">Last Name</label>
					<input type="text" class="form-control" id="phone" placeholder="Enter last name" name="last_name" value="{{custom_user.last_name}}">
				</div>
			</div>
			<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
				<div class="form-group">
					<label for="website">Phone</label>
					<input type="text" class="form-control" id="website" placeholder="Enter phone number" name="phone" value="{{custom_user.phone}}">
				</div>
			</div>

		</div>
		<div class="row gutters">
			<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
				<h6 class="mt-3 mb-2 text-primary">Address</h6>
			</div>
			<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
				<div class="form-group">
					<label for="Street">Street</label>
					<input type="text" class="form-control" id="street" placeholder="Enter Street" name="street" value="{{custom_user.street}}">
				</div>
			</div>
			<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
				<div class="form-group">
					<label for="ciTy">City</label>
					<input type="text" class="form-control" id="ciTy" placeholder="Enter City" name="city" value="{{custom_user.city}}">
				</div>
			</div>
			<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
				<div class="form-group">
					<label for="sTate">State</label>
					<input type="text" class="form-control" id="sTate" placeholder="Enter State" name="state" value="{{custom_user.state}}">
				</div>
			</div>
			<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
				<div class="form-group">
					<label for="zIp">Zip Code</label>
					<input type="text" class="form-control" id="zIp" placeholder="Zip Code" name="zip_code" value="{{custom_user.zip_code}}">
				</div>
			</div>

		</div>
			<div class="row gutters">
			<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
				<h6 class="mt-3 mb-2 text-primary">Avatar</h6>
					<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
				<div class="form-group">
					<input type="file" class="form-control" name="image" accept="image/*"  id="id_image">
				</div>
			</div>
			</div>
		<div class="row gutters">
			<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
				<div class="text-right">
					<button type="button"  onclick="location.href='{% url 'home'  %}'" id="submit" name="submit" class="btn btn-secondary">Cancel</button>
					<button type="submit" id="submit" name="submit" class="btn btn-primary ">Update</button>
				</div>
			</div>
		</div>
	</div>
		</div>
		</form>
</div>
</div>
</div>
</div>

{% endblock content %}

templates/user/userdetailsadmin.html
{% extends 'base.html' %}
{% block content %}


<style>
body{}
.card-style1 {
    box-shadow: 0px 0px 10px 0px rgb(89 75 128 / 9%);
}
.border-0 {
    border: 0!important;
}
.card {
    position: relative;
    display: flex;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 1px solid rgba(0,0,0,.125);
    border-radius: 0.25rem;
}

    .card img{
            max-width: 100%;

            object-fit: cover;
    }

section {
    padding: 120px 0;
    overflow: hidden;
    background: #fff;
}
.mb-2-3, .my-2-3 {
    margin-bottom: 2.3rem;
}

.section-title {
    font-weight: 600;
    letter-spacing: 2px;
    text-transform: uppercase;
    margin-bottom: 10px;
    position: relative;
    display: inline-block;
}
.text-primary {
    color: #ceaa4d !important;
}
.text-secondary {
    color: #15395A !important;
}
.font-weight-600 {
    font-weight: 600;
}
.display-26 {
    font-size: 1.3rem;
}


}
.p-1-9 {
    padding: 1.9rem;
}

.bg-secondary {
    background: #15395A !important;
}

.pe-1-9, .px-1-9 {
    padding-right: 1.9rem;
}
.ps-1-9, .px-1-9 {
    padding-left: 1.9rem;
}
.pb-1-9, .py-1-9 {
    padding-bottom: 1.9rem;
}
.pt-1-9, .py-1-9 {
    padding-top: 1.9rem;
}
.mb-1-9, .my-1-9 {
    margin-bottom: 1.9rem;
}
.rounded {
    border-radius: 0.25rem!important;
}
</style>

<section class="bg-light">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 mb-4 mb-sm-5">
                <div class="card card-style1 border-0">
                    <div class="card-body p-1-9 p-sm-2-3 p-md-6 p-lg-7">
                        <div class="row align-items-center">
                            <div class="col-lg-6 mb-4 mb-lg-0">
                                <img src={{custom_user.image.url}} alt="...">
                            </div>
                            <div class="col-lg-6 px-xl-10">
                                <div class="bg-secondary d-lg-inline-block py-1-9 px-1-9 px-sm-6 mb-1-9 rounded">
                                    <h3 class="h2 text-white mb-0">{{custom_user.first_name}} {{custom_user.last_name}}</h3>
                                    <span class="text-primary">{{custom_user.user.email}}</span>
                                </div>
                                <ul class="list-unstyled mb-1-9">
                                    <li class="mb-2 mb-xl-3 display-28"><span class="display-26 text-secondary me-2 font-weight-600">Phone:</span>{{custom_user.phone}}</li>
                                    <li class="mb-2 mb-xl-3 display-28"><span class="display-26 text-secondary me-2 font-weight-600">Street:</span>{{custom_user.street}}</li>
                                    <li class="mb-2 mb-xl-3 display-28"><span class="display-26 text-secondary me-2 font-weight-600">City:</span>{{custom_user.city}}</li>
                                    <li class="mb-2 mb-xl-3 display-28"><span class="display-26 text-secondary me-2 font-weight-600">State:</span>{{custom_user.state}}</li>
                                    <li class="mb-2 mb-xl-3 display-28"><span class="display-26 text-secondary me-2 font-weight-600">Zip code:</span>{{custom_user.zip_code}}</li>
                                </ul>
                                <ul class="social-icon-style1 list-unstyled mb-0 ps-0">
                                    <li><a href="#!"><i class="ti-twitter-alt"></i></a></li>
                                    <li><a href="#!"><i class="ti-facebook"></i></a></li>
                                    <li><a href="#!"><i class="ti-pinterest"></i></a></li>
                                    <li><a href="#!"><i class="ti-instagram"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}